// Generated by dts-bundle-generator v9.5.1

export interface CookieOptions {
	expires?: number | Date | false;
	domain?: string | false;
	path?: string;
	secure?: boolean;
	nulltoremove?: boolean;
	autojson?: boolean;
	autoencode?: boolean;
	encode?: (val: string) => string;
	decode?: (val: string) => string;
	fallback?: ((key: string, opt: CookieOptions) => unknown) | false;
	test?: (cookie: string) => void;
}
export interface CookiesFn extends CookieOptions {
	(): CookiesFn;
	(data: string): unknown;
	(data: Record<string, unknown>, opt?: CookieOptions): CookiesFn;
}
declare const cookies: CookiesFn;

export {
	cookies as default,
};

export {};
